### API Server test
### GET (all)
http://localhost:9000/.netlify/functions/server/api/users

### GET (by id)
http://localhost:9000/.netlify/functions/server/api/projects/2

### POST
POST http://localhost:9000/.netlify/functions/server/api/users HTTP/1.1
content-type: application/json

{
 "firstName": "Harry",
 "email": "hpotter@hogwarts.edu"
}


### PUT
PUT http://localhost:9000/.netlify/functions/server/api/users/4 HTTP/1.1
content-type: application/json

{
  "firstName": "George",
  "lastName": "Kaplan",
  "email": "george@gmail.com",
  "cohort": "WEBPT4",
  "project_manager": "Anthony"
}


### DELETE
DELETE http://localhost:9000/.netlify/functions/server/api/projects/2
